motion_noise_scale = 2
initial_position_std_meters = 0.1
initial_vel_std_meters_per_sec = 1.0
ekf_observation_covariance_pixels = 10
accept_observation_min_likelihood = 1e-14
max_position_std_meters = 0.5

[hypothesis_test_params]
hypothesis_test_max_acceptable_error = 5.0
minimum_number_of_cameras = 2
minimum_pixel_abs_zscore = 0.0
